######################################################################
# Automatically generated by qmake (2.01a) pon. sty 21 00:29:16 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h levelboard.h pacmanarena.h player.h
SOURCES += gameboard.cpp main.cpp pacmanarena.cpp player.cpp
