######################################################################
# Automatically generated by qmake (2.01a) wt. sty 22 14:44:20 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h pacmanarena.h player.h
SOURCES += gameboard.cpp main.cpp pacmanarena.cpp player.cpp
