######################################################################
# Automatically generated by qmake (2.01a) niedz. sty 20 22:05:38 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gameboard.h levelboard.h pacmanarena.h
SOURCES += gameboard.cpp main.cpp pacmanarena.cpp
